blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/padparadscho/gnome-shell-focused-app-extension/blob/main/README.md
    about: Comprehensive documentation for the gnome-shell-focused-app-extension repository.
  - name: GitHub Discussions
    url: https://github.com/padparadscho/gnome-shell-focused-app-extension/discussions
    about: Ask questions, share ideas, and discuss with the community on GitHub.
  - name: X (Twitter)
    url: https://x.com/padparadscho
    about: Follow Padparadscho on X (Twitter) for updates, discussions or just to say hi!
